// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Rivukj8ZwA4tmC8LWgaoqIl8NJLDAzk',
    appId: '1:866671808271:web:6f9ce8618687293f10787a',
    messagingSenderId: '866671808271',
    projectId: 'fir-learning-23cdd',
    authDomain: 'fir-learning-23cdd.firebaseapp.com',
    storageBucket: 'fir-learning-23cdd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN6dgTZMbW3qcJnKDVmlG6jIbFwWiTzjs',
    appId: '1:866671808271:android:9dae1c3532dbf23510787a',
    messagingSenderId: '866671808271',
    projectId: 'fir-learning-23cdd',
    storageBucket: 'fir-learning-23cdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAktw7bXPMk6A6GBgpS2uk78JNms3dcS2Q',
    appId: '1:866671808271:ios:f421950af4838bea10787a',
    messagingSenderId: '866671808271',
    projectId: 'fir-learning-23cdd',
    storageBucket: 'fir-learning-23cdd.firebasestorage.app',
    iosBundleId: 'com.example.firebaselearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAktw7bXPMk6A6GBgpS2uk78JNms3dcS2Q',
    appId: '1:866671808271:ios:f421950af4838bea10787a',
    messagingSenderId: '866671808271',
    projectId: 'fir-learning-23cdd',
    storageBucket: 'fir-learning-23cdd.firebasestorage.app',
    iosBundleId: 'com.example.firebaselearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6Rivukj8ZwA4tmC8LWgaoqIl8NJLDAzk',
    appId: '1:866671808271:web:9989b16f8684c9e810787a',
    messagingSenderId: '866671808271',
    projectId: 'fir-learning-23cdd',
    authDomain: 'fir-learning-23cdd.firebaseapp.com',
    storageBucket: 'fir-learning-23cdd.firebasestorage.app',
  );
}
